### ISSUE TITLE
Error: OSError: skywork/skywork-13b-chat is not a local folder

### ISSUE THREAD

**Issue by ZorkJ** [SkyworkAI/Skywork#12]
When I use the sample code, there are some errors.

OSError: skywork/skywork-13b-chat is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo with `use_auth_token` or log in with `huggingface-cli login` and pass `use_auth_token=True`

**Comment by zhao1iang** [comment]
Our Skywork-13B-Chat model is still undergoing careful alignment to ensure that the generated results are harmful.  “skywork/skywork-13b-chat” is the downloaded directory for the Skywork-13B-Chat model. Thanks for your feedback. Please try our this sample code  again after our chat model is released.

**Comment by ZorkJ** [comment]
Thanks for your reply. Can we use the base model for chating-similar work? Like one question, one answer.

**Comment by TianwenWei** [comment]
The base model is a completion model. It tends to _complete_ your question rather than _answer_ it. In that regard, I do not believe that it can do chating similar work reliably.

I strongly advice you to wait for our Skywork-13B-Chat, which will most likely be released in November..
