### ISSUE TITLE
会支持更多的上下文吗，目前是4k吧

### ISSUE THREAD

**Issue by RipperTs** [SkyworkAI/Skywork#17]

**Comment by zhao1iang** [comment]
您可以通过YaRN，PI，NTK等方法可以通过少量微调轻松将基于RoPE position embedding的模型（包括我们模型）扩展到32K以上。如果您没有机器资源进行微调，可以使用DynamicNTK的方法不需要微调也可以扩展到16K左右 ，您如果有需求的话，可以先尝试这些方法进行长上下文扩展。
