### ISSUE TITLE
请问中文数据集是否有大陆可方便下载地址？

### ISSUE THREAD

**Issue by hxf829** [SkyworkAI/Skywork#19]
谢谢

**Comment by dancymax73** [comment]
同问，中国人做的中文数据集在中国下载不了，有点闹心啊

**Comment by dancymax73** [comment]
同求，同胞们很需要啊，huggingface在国内很难打开

**Comment by sz128** [comment]
https://hf-mirror.com/

**Comment by HaimianYu** [comment]
有已经下载了的吗？能不能分享下。

**Comment by dancymax73** [comment]
后续回答已经有了，可以采用huggingface的镜像站，你没看到吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月8日(周三) 中午11:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SkyworkAI/Skywork] 请问中文数据集是否有大陆可方便下载地址？ (Issue #19)




 
有已经下载了的吗？能不能分享下。

**Comment by dancymax73** [comment]
好的，非常感谢！



---原始邮件---
发件人: "Su ***@***.***&gt;
发送时间: 2023年11月4日(周六) 上午10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [SkyworkAI/Skywork] 请问中文数据集是否有大陆可方便下载地址？ (Issue #19)




 
https://hf-mirror.com/

**Comment by HaimianYu** [comment]
不行呀，没有镜像

**Comment by sz128** [comment]
> 不行呀，没有镜像

主站也看不到了。

**Comment by ibmarzhu** [comment]
有下载的兄弟能分享一份吗？

**Comment by TianwenWei** [comment]
国内下载点已开放，始智AI：
https://www.wisemodel.cn/datasets/Skywork/SkyPile-150B/
