### ISSUE TITLE
Skywork-13B-Chat 

### ISSUE THREAD

**Issue by Tonsjkjkas** [SkyworkAI/Skywork#22]
Hi,When will Skywork-13B-Chat be released?

**Comment by Tonsjkjkas** [comment]
Besides, is there a plan for the release of Skywork-13B-MM?

**Comment by TianwenWei** [comment]
Our Skywork-13B-Chat and MM models are still undergoing careful alignment to ensure that the generated results are harmless. If everything goes well, those model will be released by the end of November.

**Comment by jhj033** [comment]
> Our Skywork-13B-Chat and MM models are still undergoing careful alignment to ensure that the generated results are harmless. If everything goes well, those model will be released by the end of November.

Good News.

**Comment by Tonsjkjkas** [comment]
> > Our Skywork-13B-Chat and MM models are still undergoing careful alignment to ensure that the generated results are harmless. If everything goes well, those model will be released by the end of November.
> 
> Good News.

I also think so. Skywork-13B-Chat is an expected model.
