### ISSUE TITLE
TypeError: can only concatenate tuple (not "str") to tuple

### ISSUE THREAD

**Issue by QuanhuiGuan** [SkyworkAI/Skywork#26]
TypeError: can only concatenate tuple (not "str") to tuple

**Comment by zhao1iang** [comment]
您能运行的脚本和命令是什么呢，在哪一行出现了错误呢？

**Comment by QuanhuiGuan** [comment]
Thank you for your asking, it seems that I make a mistake.

**Comment by zhliuworks** [comment]
pip install -U datasets
