### ISSUE TITLE
请问您开源的150B数据集huggingface上怎么不能下载了？

### ISSUE THREAD

**Issue by sunzhuojun** [SkyworkAI/Skywork#30]
谢谢

**Comment by bltcn** [comment]
同问

**Comment by zhangxiaofan-zy** [comment]
同问

**Comment by yw10** [comment]
Skywork: A More **Open** Bilingual Foundation Model

404
Sorry, we can't find the page you are looking for.

**Comment by grapefruit-pig** [comment]
同问

**Comment by kbwzy** [comment]
同问

**Comment by zhao1iang** [comment]
法务老师需要评估数据集的风险，等待确认完成后会开放哈

**Comment by onlyfew** [comment]
预计要评估多久呢？ @zhao1iang

**Comment by auuuux** [comment]
同问

**Comment by ForeverNewLee** [comment]
同问，或者目前有别的可下载的地方么

**Comment by TianwenWei** [comment]
应该一两周内数据集会重新open

**Comment by spicy-onion-Hit** [comment]
同求

**Comment by genggui001** [comment]
一周过去了，再求

**Comment by TianwenWei** [comment]
有关部门正在审核数据，还请大家谅解

**Comment by datalee** [comment]
同问

**Comment by ChanChiChoi** [comment]
同问

**Comment by TianwenWei** [comment]
https://huggingface.co/datasets/Skywork/SkyPile-150B
我们的数据集安全审核后已重新开放，造成的不便敬请谅解。

**Comment by genggui001** [comment]
> https://huggingface.co/datasets/Skywork/SkyPile-150B 我们的数据集安全审核后已重新开放，造成的不便敬请谅解。

我对比了一下之前下载的版本 有不少文件少了一半还多 正常的？

**Comment by TianwenWei** [comment]
> > https://huggingface.co/datasets/Skywork/SkyPile-150B 我们的数据集安全审核后已重新开放，造成的不便敬请谅解。
> 
> 我对比了一下之前下载的版本 有不少文件少了一半还多 正常的？

根据国家法律法规我们删除了一些有安全风险的内容，另外补充了一些新数据。
