### ISSUE TITLE
请问能不能测试下GPT-4的 L_{test} - L_{train}

### ISSUE THREAD

**Issue by wxj630** [SkyworkAI/Skywork#31]
L_{test} - L_{train}，想知道GPT-4是不是也见过了训练集，所以严格来说GPT-4也不能完全说是zero-shot ?

**Comment by callanwu** [comment]
mark

**Comment by zhao1iang** [comment]
L_{test} - L_{train}需要获取模型logits计算loss，但目前GPT-4只输出答案并不能输出logits。

**Comment by wxj630** [comment]
ok谢谢解答
