### ISSUE TITLE
请问测试数据会公开么？

### ISSUE THREAD

**Issue by 4IK1d** [SkyworkAI/Skywork#46]
如题，谢谢。

**Comment by TianwenWei** [comment]
> 如题，谢谢。

请问您说的什么测试数据？

**Comment by tq-xyy** [comment]
我觉得应该不会公开，因为如果公开了又会造成数据集污染。这是 Skywork 团队不想看到的。
如果要公开的话一定会把下一代数据集准备好。

**Comment by zhao1iang** [comment]
您好，我们用于和其他模型对比的多领域测试数据和检测模型真实数学能力的mock_gsm8k_test数据均已公开。下面是测试集的地址：https://huggingface.co/datasets/Skywork/ChineseDomainModelingEval, https://huggingface.co/datasets/Skywork/mock_gsm8k_test。

**Comment by 4IK1d** [comment]
> 您好，我们用于和其他模型对比的多领域测试数据和检测模型真实数学能力的mock_gsm8k_test数据均已公开。下面是测试集的地址：https://huggingface.co/datasets/Skywork/ChineseDomainModelingEval, [https://huggingface.co/datasets/Skywork/mock_gsm8k_test。](https://huggingface.co/datasets/Skywork/mock_gsm8k_test%E3%80%82)

多谢多谢

**Comment by 4IK1d** [comment]
> > 如题，谢谢。
> 
> 请问您说的什么测试数据？

指上述测评数据集

**Comment by 4IK1d** [comment]
是我漏看了readme，11.2已经更新了发布信息
