### ISSUE TITLE
评测数据集MOCK_GSM8K_TEST使用方式

### ISSUE THREAD

**Issue by cafeii** [SkyworkAI/Skywork#54]
您好，我正在尝试在其他模型上复现该实验，想请问在这个实验中，这个数据集的使用方式是否与原版的GSM8k有所不同？因为我没有看到有question相关的prompt部分

**Comment by zhao1iang** [comment]
MOCK_GSM8K_TEST集和用于衡量语言模型的损失，所以是question和answer拼接起来的，当成一个文档。原版的GSM8K train和 test也需要将question和answer拼接起来。
