### ISSUE TITLE
当前eval_loss脚本不支持chatglm系列模型

### ISSUE THREAD

**Issue by wbq9224** [SkyworkAI/Skywork#64]
如题，当前eval_loss脚本不支持chatglm系列模型。可否补上相关评测。
或者怎么改支持呢，我试了下好像chatglm的tokenizer属性不太一致，并且padding_side也和eval中写的不一样，导致强行用这个脚本测出的loss是inf。

**Comment by zhao1iang** [comment]
您好，最新的脚本已添加对chatglm3的支持，我本地跑了一下，loss是正常的。
