### ISSUE TITLE
官方提供 磁力链接 数据源吗

### ISSUE THREAD

**Issue by hggq** [SkyworkAI/Skywork#66]
Mistral AI 昨天发布了一条仅包含磁力链接的推文，很有启发意义。
网友打开该磁力链接后发现居然是一个大小为 87 GB 的种子。从命名和目录结构来看，这是一个 PyTorch 模型文件。
Mistral AI 这次 “开源” 的 mixtral-8x7b-32kseqlen 是一个基于混合专家 (Mixture of Experts, MoE) 的大模型，由 8 个 70 亿参数规模 (8×7b) 的专家网络组成。据称是全球首个开源 MoE 大模型

我感觉应该绕开 Hugging Face

这样中国地区可以快速下载

**Comment by TianwenWei** [comment]
您好，近期我们会放一个国内的源方便从国内下载。现在正在上传但速度有点慢还请耐心等待。

**Comment by huangyc0618** [comment]
压缩一下？上传下载快一些

**Comment by hggq** [comment]
我花了2个小时，下载，我感觉挺方便的，可以学他们也去发一个帖子，带上磁力链接，这样也不占用服务器资源。

**Comment by TianwenWei** [comment]
国内下载点已开放，始智AI：
https://www.wisemodel.cn/datasets/Skywork/SkyPile-150B/

**Comment by hggq** [comment]
能提供一个磁力链接吗？那样也方便。

**Comment by liuyijiang1994** [comment]
能提供一个磁力链接吗？那样也方便。
