### ISSUE TITLE
论文链接是百川大模型的技术报告

### ISSUE THREAD

**Issue by chenshipku** [SkyworkAI/Skywork#7]
url arXiv: 2309.10305是百川大模型的技术报告

@article{skyworkmath,
  title={SkyMath: Technical Report},
  author={Liu Yang, Haihua Yang, Wenjun Cheng, Lei Lin, Chenxia Li, Yifu Chen, Lunan Liu, Jianfei Pan, Tianwen Wei, Biye Li, Liang Zhao, Lijie Wang, Bo Zhu, Guoliang Li, Xuejie Wu, Xilin Luo, Rui Hu},
  journal={arXiv preprint arXiv: 2310.16713},
  url={https://arxiv.org/abs/2309.10305},
  year={2023}
}

**Comment by zhao1iang** [comment]
URL错误已修复

**Comment by zhao1iang** [comment]
感谢您的反馈，URL错误的问题已修复，就先关闭这个Issue了
