### ISSUE TITLE
SkyPile-150B数据集的重复率有点小高

### ISSUE THREAD

**Issue by genggui001** [SkyworkAI/Skywork#72]
SkyPile-150B数据集的重复率有点小高
我用slimpajama里面的deduplicate代码跑了一波，很多文件的重复率都在50%以上
有点神奇

**Comment by TianwenWei** [comment]
是有一些重复，我们当时使用的时候没有检测出来。如果去重的话数据集可以瘦身30%。

**Comment by fyubang** [comment]
> 是有一些重复，我们当时使用的时候没有检测出来。如果进一步严格去重的话数据集可以瘦身30%。

我试了一下，好像精确去重就能去掉40%，是不是数据集上传的有点问题啊？
