### ISSUE TITLE
ppl 的测试脚本只输出了 loss，不输出 ppl？

### ISSUE THREAD

**Issue by SefaZeng** [SkyworkAI/Skywork#74]
readme 里面提到最终的 ppl 是由 loss_a * token_a / token_s，但是 token_s 是自己手动分词再算吗？为什么不在 eval_loss.py 里面指出输出最终的 ppl 呢？

**Comment by zhao1iang** [comment]
是的，需要先算出token_s。PPL和loss是一回事，将loss取指数就是PPL了。

**Comment by SefaZeng** [comment]
> 是的，需要先算出token_s。PPL和loss是一回事，将loss取指数就是PPL了。

理解，我的意思是既然只差最后一步，可以在脚本里把 ppl 算出来，就不用在 Readme 里面解释计算细节了。也避免最后复现的时候 loss 是对的 ppl 算不对的情况。

**Comment by zhao1iang** [comment]
好的，后续会对计算进行改进，会更加方便
